### ISSUE TITLE
初始化报错，以及postCatchedException的问题

### ISSUE THREAD

**Issue by luokunman** [crazecoder/flutter_bugly#121]
当我第一次初始化时候，会报一个java的错  ，第二次加载又不会了
```text
W/CrashReport( 7172): java.io.IOException: unknown format (magic number 0)
W/CrashReport( 7172): 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:109)
W/CrashReport( 7172): 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:88)
W/CrashReport( 7172): 	at com.tencent.bugly.proguard.ia.b(BUGLY:2)
W/CrashReport( 7172): 	at com.tencent.bugly.proguard.ca.a(BUGLY:49)
W/CrashReport( 7172): 	at com.tencent.bugly.proguard.U.run(BUGLY:72)
W/CrashReport( 7172): 	at com.tencent.bugly.proguard.S.run(BUGLY:3)
W/CrashReport( 7172): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/CrashReport( 7172): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/CrashReport( 7172): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
W/CrashReport( 7172): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
W/CrashReport( 7172): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/CrashReport( 7172): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/CrashReport( 7172): 	at java.lang.Thread.run(Thread.java:818)
```
似乎是调用Unzip解压的过程报错
也可以成功运行程序
```text
D/CrashReport( 7172): [Upload] Response cmd is: 0, length of sBuffer is: 0
I/CrashReport( 7172): [Upload] Success: 804
```
postCatchedException能否不在main中。因为在上架项目时，同意《用户协议》弹框之前，不允许加载任何的sdk

**Comment by crazecoder** [comment]
postCatchedException并不代表会初始化，init可以在任何地方调用，但是在调用之前如果报错不会上报

**Comment by luokunman** [comment]
> postCatchedException并不代表会初始化，init可以在任何地方调用，但是在调用之前如果报错不会上报

好的   这几天研究了下  大概懂了  谢谢~
