### ISSUE TITLE
flutter升级后的异常

### ISSUE THREAD

**Issue by qq125183592** [crazecoder/flutter_bugly#50]
当前环境flutter升级后的版本号为：Flutter 1.5.4-hotfix.2
bugly版本：flutter_bugly: ^0.2.3

然后在使用插件做更新时会触发以下异常，能否协助看看：

```
I/flutter (18717): 0===1562652127
E/MethodChannel#crazecoder/flutter_bugly(18717): Failed to handle method call
E/MethodChannel#crazecoder/flutter_bugly(18717): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at com.crazecoder.flutterbugly.FlutterBuglyPlugin.onMethodCall(FlutterBuglyPlugin.java:137)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at android.os.MessageQueue.next(MessageQueue.java:330)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at android.os.Looper.loop(Looper.java:137)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at android.app.ActivityThread.main(ActivityThread.java:5546)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
E/MethodChannel#crazecoder/flutter_bugly(18717): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
E/CrashReport(18717): Java Catch Happen
I/System.out(18717): [logcat, -d, -v, threadtime]
I/System.out(18717): null
I/System.out(18717): null
I/System.out(18717): Calling by::className:com.tencent.bugly.proguard.aq  MethodName:a
I/CrashReport(18717): [LogUtil] Get user log from native.
I/CrashReport-Native(18717): Native log has not been initiated.
I/CrashReport(18717): user log size:0
E/CrashReport(18717): stack frame :161, has cause false
E/CrashReport(18717): #++++++++++Record By Bugly++++++++++#
E/CrashReport(18717): # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
E/CrashReport(18717): # PKG NAME: com.letabc.zaxt
E/CrashReport(18717): # APP VER: 0.0.4
E/CrashReport(18717): # LAUNCH TIME: 2019-07-09 14:01:02
E/CrashReport(18717): # CRASH TYPE: JAVA_CATCH
E/CrashReport(18717): # CRASH TIME: 2019-07-09 14:02:11
E/CrashReport(18717): # CRASH PROCESS: com.letabc.zaxt
E/CrashReport(18717): # CRASH THREAD: main
E/CrashReport(18717): # REPORT ID: e10355b2-7eb6-4186-964b-92e09d06872d
E/CrashReport(18717): # CRASH DEVICE: HUAWEI MT7-TL10 UNROOT
E/CrashReport(18717): # RUNTIME AVAIL RAM:1918181376 ROM:12407660544 SD:12386689024
E/CrashReport(18717): # RUNTIME TOTAL RAM:3158274048 ROM:27691012096 SD:27670040576
E/CrashReport(18717): # CRASH STACK: 
E/CrashReport(18717): java.lang.Throwable: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null)
E/CrashReport(18717): 	at Dart.0      StandardMethodCodec.decodeEnvelope(package:flutter/src/services/message_codecs.dart:564)
E/CrashReport(18717): 	at Dart.1      MethodChannel.invokeMethod(package:flutter/src/services/platform_channel.dart:302)
E/CrashReport(18717): 	at Dart.2      FlutterBugly.checkUpgrade(package:flutter_bugly/src/flutter_bugly.dart:100)
E/CrashReport(18717): 	at Dart.3      HomePageState.upgradeApk(package:flutter_app/pages/public/home.dart:119)
E/CrashReport(18717): 	at Dart.4      HomePageState.initState(package:flutter_app/pages/public/home.dart:63)
E/CrashReport(18717): 	at Dart.5      StatefulElement._firstBuild(package:flutter/src/widgets/framework.dart:3846)
E/CrashReport(18717): 	at Dart.6      ComponentElement.mount(package:flutter/src/widgets/framework.dart:3717)
E/CrashReport(18717): 	at Dart.7      Element.inflateWidget(package:flutter/src/widgets/framework.dart:2961)
E/CrashReport(18717): 	at Dart.8      Element.updateChild(package:flutter/src/widgets/framework.dart:2764)
E/CrashReport(18717): 	at Dart.9      SingleChildRenderObjectElement.mount(package:flutter/src/widgets/framework.dart:4876)
E/CrashReport(18717): 	at Dart.10     Element.inflateWidget(package:flutter/src/widgets/framework.dart:2961)
E/CrashReport(18717): 	at Dart.11     Element.updateChild(package:flutter/src/widgets/framework.dart:2764)
E/CrashReport(18717): 	at Dart.12     SingleChildRenderObjectElement.mount(package:flutter/src/widgets/framework.dart:4876)
E/CrashReport(18717): 	at Dart.13     Element.inflateWidget(package:flutter/src/widgets/framework.dart:2961)
E/CrashReport(18717): 	at Dart.14     Element.updateChild(package:flutter/src/widgets/framework.dart:2764)
E/CrashReport(18717): 	at Dart.15     ComponentElement.performRebuild(package:flutter/src/widgets/framework.dart:3750)
E/CrashReport(18717): 	at Dart.16     Element.rebuild(package:flutter/src/widgets/framework.dart:3565)
E/CrashReport(18717): 	at Dart.17     ComponentElement._firstBuild(package:flutter/src/widgets/framework.dart:3722)
E/CrashReport(18717): 	at Dart.18     ComponentElement.mount(package:flutter/src/widgets/framework.dart:3717)
E/CrashReport(18717): 	at Dart.19     Element.inflateWidget(package:flutter/src/widgets/framework.dart:2961)
E/CrashReport(18717): 	at Dart.20     Element.updateChild(package:flutter/src/widgets/framework.dart:2764)
E/CrashReport(18717): 	at Dart.21     ComponentElement.performRebuild(package:flutter/src/widgets/framework.dart:3750)
E/CrashReport(18717): 	at Dart.22     Element.rebuild(package:flutter/src/widgets/framework.dart:3565)
E/CrashReport(18717): 	at Dart.23     ComponentElement._firstBuild(package:flutter/src/widgets/framework.dart:3722)
E/CrashReport(18717): 	at Dart.24     ComponentElement.mount(package:flutter/src/widgets/framework.dart:3717)
E/CrashReport(18717): 	at Dart.25     ParentDataElement.mount(package:flutter/src/widgets/framework.dart:4063)
E/CrashReport(18717): 	at Dart.26     Element.inflateWidget(package:flutter/src/widgets/framework.dart:2961)
E/CrashReport(18717): 	at Dart.27     Element.updateChild(package:flutter/src/widgets/framework.dart:2764)
E/CrashReport(18717): 	at Dart.28     ComponentElement.performRebuild(package:flutter/src/widgets/framework.dart:3750)
E/CrashReport(18717): 	at Dart.29     Element.rebuild(package:flutter/src/widgets/framework.dart:3565)
E/CrashReport(18717): 	at Dart.30     ComponentElement._firstBuild(package:flutter/src/widgets/framework.dart:3722)
E/CrashReport(18717): 	at Dart.31     StatefulElement._firstBuild(package:flutter/src/widgets/framework.dart:3864)
E/CrashReport(18717): 	at Dart.32     ComponentElement.mount(package:flutter/src/widgets/framework.dart:3717)
E/CrashReport(18717): 	at Dart.33     Element.inflateWidget(package:flutter/src/widgets/framework.dart:2961)
E/CrashReport(18717): 	at Dart.34     Element.updateChild(package:flutter/src/widgets/framework.dart:2764)
E/CrashReport(18717): 	at Dart.35     SliverMultiBoxAdaptorElement.updateChild(package:flutter/src/widgets/sliver.dart:1034)
E/CrashReport(18717): 	at Dart.36     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>(package:flutter/src/widgets/sliver.dart:1019)
E/CrashReport(18717): 	at Dart.37     BuildOwner.buildScope(package:flutter/src/widgets/framework.dart:2258)
E/CrashReport(18717): 	at Dart.38     SliverMultiBoxAdaptorElement.createChild(package:flutter/src/widgets/sliver.dart:1012)
E/CrashReport(18717): 	at Dart.39     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:275)
E/CrashReport(18717): 	at Dart.40     RenderObject.invokeLayoutCallback.<anonymous closure>(package:flutter/src/rendering/object.dart:1740)
E/CrashReport(18717): 	at Dart.41     PipelineOwner._enableMutationsToDirtySubtrees(package:f
E/CrashReport(18717): #++++++++++++++++++++++++++++++++++++++++++#
I/CrashReportInfo(18717): [crash] a caught exception occur, handling...
I/CrashReportInfo(18717): [crash] save crash success
I/CrashReport(18717): try to upload right now
I/System  (18717): core_booster, getBoosterConfig = false
I/CrashReport(18717): [Upload] Success: crash
```

**Comment by crazecoder** [comment]
粗心了。。。

**Comment by qq125183592** [comment]
0.2.3+1 已解决～ 多谢作者
